[package]
name = "rust-webserver"
version = "0.1.1"
edition = "2023"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"

[profile.release]
strip = true
lto = true
codegen-units = 1
panic = "abort"
